### ISSUE TITLE
Each Election Period should have a capacity to receive only fixed number of proposal? 

### ISSUE THREAD

**Issue by 0xbeny** [XinFinOrg/osx-daofin#20]

**Comment by 08-RED** [comment]
yes, since generating a proposal involves a fee to create then we are expecting less spam proposals or none at all. 

But we may need to consider that these proposals will start pouring in at the very last month / week of the election period? This will be a challenge for the community / Jury to do all necessary due diligence in a limited timeframe.

Suggestion: As the deadline for the final submission approaches, the maximum capacity for proposals should also decrease, regardless if proposals are being submitted or not.

**Comment by 0xbeny** [comment]
Capacity helps all the committees to spend enough time on each proposal in high traffic timelines.
Additionally, helps to Jury to arrange and manage community calls easier.

> Suggestion: As the deadline for the final submission approaches, the maximum capacity for proposals should also decrease, regardless if proposals are being submitted or not.

Daofin considers "capacity" as a parameter(can be configurable, to change that we need a new type of proposal) and "Election period" as A timeframe to B timeframe. i think that makes it more complicated. since we don't have any idea how many proposals are going to send on DAOFIN. Thanks for suggestion, i'm keeping it in my mind once we see that traffic.

Would like to receive more feedback on this.

**Comment by 08-RED** [comment]
Clarification on my post to avoid confusion. I think i'm getting confused with terms.

The election period I was referring is the time that people are allowed to create proposals. Example - quarterly. This is different to the "Voting time", where proposals will no longer be accepted.

For my point above, let's say the Election period is quarterly, eg. January, February, March. Voting time is set to 3rd - 4th week of March. The maximum capacity of proposal in that quarter is set to 100, as an example. Since we do not know when these proposals will be created, what if all 100 proposals were created on month of March, or worse the 100 proposals were created on 2nd week of March? This will only give 1 week for everyone to review 100 proposals. It's far-fetch, but it could happen. So I am suggesting allocation of # of  proposals out of the maximum capacity. The maximum capacity of proposals must decrease as the Voting Time approaches.

**Comment by SeanXDCAustralia** [comment]
What about a disclaimer that the jury has the right to create a "Cut off"
in real time..OR the Grant period ends 4 weeks earlier than the Quarter - to allow for assessment.

**Comment by 0xbeny** [comment]
This Idea completely defeated. Anyone can create any number of proposal for a specific Election periods.
The Role of community here is to manage the traffic and the need for the network.
